### ISSUE TITLE
windows环境执行hello word直接报错，是否不支持windows环境下运行哪？

### ISSUE THREAD

**Issue by PepperPapa** [dechenx83/automation_test#2]
我在windows环境下执行demo用例，直接报错，报错信息如下：
D:\automation_test\userinterface>python start.py -s settingfile -t ../example/demo_list.testlist -r ../example/resource.json -u dechen    
Traceback (most recent call last):
  File "start.py", line 8, in <module>
    from controller.manager import *
  File "D:\myrepo\automation_test\userinterface\..\controller\manager.py", line 4, in <module>
    from core.testengine.caserunner import CaseRunner
  File "D:\myrepo\automation_test\userinterface\..\core\testengine\caserunner.py", line 13, in <module>
    from core.resource.pool import ResourcePool
  File "D:\myrepo\automation_test\userinterface\..\core\resource\pool.py", line 296, in <module>
    class ResourceSetting(SettingBase):
  File "D:\myrepo\automation_test\userinterface\..\core\resource\pool.py", line 299, in ResourceSetting
    resource_path = os.path.join(os.environ['HOME'], "test_resource")
  File "C:\Users\Think\AppData\Local\Programs\Python\Python38-32\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'

**Comment by jingling2009** [comment]
在windows下 将HOME 替换成:HOMEPATH  就可以了。。。在Linux系统是HOME

**Comment by dechenx83** [comment]
楼上回答是对的，我的确没有考虑到windows用户的情况。
可以使用os.path.expanduser("~")来获取用户目录，或者使用HOMEPATH在windows系统中
